image: node:latest

stages:
  - deploy

pages:
    stage: deploy

    script:
        - cd my-react-app
        - npm install
        - npm run build
    
    artifacts:
        paths:
            - public
    only:
        - main
